### ISSUE TITLE
Сделать комманду для подписи на все уведомления

### ISSUE THREAD

**Issue by preved911** [sputnik-systems/alertmanager_bot#16]
Нужно сделать комманды для того, чтобы "работать" сразу со всеми алертами(`/subscribeall` и `/unsubscribeall`, например). При этом, регистрировать в конфиге алертменеджера роуты для каждой алертгруппы.
Думаю, стоит попробовать изменить формат конфига алертменеджера и описывать руоты во вложенных сущностях. Например:
```
route:
  receiver: web.hook
  group_by:
  - alertname
  continue: false
  routes:
  - receiver: "-453132248"
    match:
      alertgroup: Flussonic
    continue: true
  - receiver: "-1001315635262"
    match:
      alertgroup: Asgard.API.GQL
    continue: true
```
- сейчас
```
route:
  receiver: web.hook
  group_by:
  - alertname
  continue: false
  routes:
  - receiver: "-453132248"
    routes:
    - receiver: "-453132248"
      match:
        alertgroup: Flussonic
      continue: true
  - receiver: "-1001315635262"
    routes:
    - receiver: "-1001315635262"
      match:
        alertgroup: Asgard.API.GQL
      continue: true
```
- новый формат

Таким образом, в итоге должна быть возможность подписаться на все алертгруппы и отписаться от некоторых выборочно.
